# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Release Obsidian plugin

on:
  push:
    tags:
      - "*"

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: 'pnpm'

      - name: Build plugin
        run: |
          pnpm install
          pnpm run build
  
      - name: Prepare files
        run: |
          mkdir obsidian-markdown-tabs
          cp main.js manifest.json styles.css obsidian-markdown-tabs/

      - name: Package files
        run: |
          zip -r release.zip obsidian-markdown-tabs

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"

          gh release create "$tag" \
            --title="$tag" \
            --draft \
            release.zip
